### ISSUE TITLE
Diagrama de flujo

### ISSUE THREAD

**Issue by orgynmobs** [aigora/twIE_2021-proyecto_web_cuestionarios#3]
Debéis crear un fichero en formato [PDF](https://help.github.com/en/articles/rendering-pdf-documents), [GIF, JPEG o PNG](https://help.github.com/en/articles/rendering-and-diffing-images) (**no se admiten documentos Word o similar**) representando el [diagrama de flujo](https://es.wikipedia.org/wiki/Diagrama_de_flujo) previsto para vuestro programa. 
En el punto de inicio tenéis un [tutorial](https://github.com/aigora/punto_inicio/wiki/6.1-C%C3%B3mo-realizar-un-diagrama-de-flujo) para crear diagramas de flujo.
Este diagrama os servirá de guía para la implementación del trabajo. No obstante, ésta será la primera versión, por lo que según vayáis avanzando en el desarrollo del programa podréis y deberéis modificarlo.

**Comment by Nachofdez2708** [comment]
[DIAGRAMA_DE_FLUJO_alfa.pdf](https://github.com/aigora/twIE_2021-proyecto_web_cuestionarios/files/6249512/DIAGRAMA_DE_FLUJO_alfa.pdf)

**Comment by oscarperpinan** [comment]
El diagrama debe estar en el repositorio:
 https://teams.microsoft.com/l/message/19:db97091a60844e46a0e080f1b8195127@thread.tacv2/1617108558193?groupId=3477ddd6-cbb2-4bb5-ad31-ecefaebf2091

**Comment by Nachofdez2708** [comment]
Ya esta añadido al repositorio.
Un Saludo, 
Gracias.
